# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'draw' do
pod 'ACEDrawingView'
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
end

  # Pods for draw

  target 'drawTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'drawUITests' do
    inherit! :search_paths
    # Pods for testing
  end

